### ISSUE TITLE
Reverse Proxy examples

### ISSUE THREAD

**Issue by jameskitt616** [cameronurnes/emby-sync#6]
Would it be possible to provide some reverse proxy examples for e.g. nginx or similar.
I cannot get it running properly, it seems to sync if i configure and access it via LAN.
But if i configure it for external access it only syncs to my mobile phone, but not to other browsers.

**Comment by cameronurnes** [comment]
There's nothing special about the reverse proxy setup.  I have SSL set up for both sync.mywebsite.com and emby.mywebsite.com using fairly standard HAproxy settings in http(s) mode, sent to the correct backend based on host header matching.

**Comment by cameronurnes** [comment]
Further, there's no particular reason one client would work better than another based on this.  Its using API commands to the emby server to control the clients, the connection between the actual playing client and the emby server is fully independent of this.
